drop table if exists fixture CASCADE; 
create table fixture (id bigint generated by default as identity, 
stadium varchar(255) not null, conditions varchar(255) not null, team_size bigInt not null, 
primary key (id));